# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install hadoop --head
    - cloudtik runtime configure hadoop --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install hadoop
    - cloudtik runtime configure hadoop

# Command to start on the head node. You don't need to change this.
head_start_commands: []

# Command to start on worker nodes. You don't need to change this.
worker_start_commands: []

# Command to start on the head node. You don't need to change this.
head_stop_commands: []

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands: []
