# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install mount --head
    - cloudtik runtime configure mount --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install mount
    - cloudtik runtime configure mount

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik runtime services mount stop --head
    - cloudtik runtime services mount start --head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik runtime services mount stop
    - cloudtik runtime services mount start

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik runtime services mount stop --head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik runtime services mount stop
