from cloudtik.core._private.service_discovery.utils import SERVICE_DISCOVERY_NODE_KIND, \
    SERVICE_DISCOVERY_NODE_KIND_HEAD, SERVICE_DISCOVERY_NODE_KIND_NODE, SERVICE_DISCOVERY_NODE_KIND_WORKER, \
    match_node_kind

HEALTH_CHECK_PORT = "port"
HEALTH_CHECK_SCRIPT = "script"
HEALTH_CHECK_NODE_KIND = SERVICE_DISCOVERY_NODE_KIND

HEALTH_CHECK_NODE_KIND_HEAD = SERVICE_DISCOVERY_NODE_KIND_HEAD
HEALTH_CHECK_NODE_KIND_WORKER = SERVICE_DISCOVERY_NODE_KIND_WORKER
HEALTH_CHECK_NODE_KIND_NODE = SERVICE_DISCOVERY_NODE_KIND_NODE


def match_health_check_node(health_check, head):
    node_kind = health_check.get(HEALTH_CHECK_NODE_KIND)
    return match_node_kind(node_kind, head)
