# A unique identifier for the cluster.
cluster_name: minio

# The workspace name
workspace_name: lab

cloudtik_wheel_url: file:///cloudtik/data/share/cloudtik-1.5.0-cp38-cp38-manylinux2014_x86_64.nightly.whl

# Cloud-provider specific configuration.
provider:
    type: virtual

auth:
    ssh_user: haifchen

available_node_types:
    head.default:
        node_config:
            instance_type:
                CPU: 4 # number of cores
                memory: 4G  # memory, for example 1024M, 1G
            data_disks:
                - /home/haifchen/working/tmp/cloudtik
            data_dirs:
                - /home/haifchen/working/data
    worker.default:
        node_config:
            instance_type:
                CPU: 4 # number of cores
                memory: 4G  # memory, for example 1024M, 1G
            data_disks:
                - /home/haifchen/working/tmp/cloudtik
            data_dirs:
                - /home/haifchen/working/data
        min_workers: 4

runtime:
    types: [nodex, consul, dnsmasq, minio]
    dnsmasq:
        default_resolver: True
    minio:
        service_on_head: False
