# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install pgpool --head
    - cloudtik runtime configure pgpool --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install pgpool
    - cloudtik runtime configure pgpool

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik runtime services pgpool stop --head
    - cloudtik runtime services pgpool start --head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik runtime services pgpool stop
    - cloudtik runtime services pgpool start

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik runtime services pgpool stop --head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik runtime services pgpool stop
