# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install minio --head
    - cloudtik runtime configure minio --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install minio
    - cloudtik runtime configure minio

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik runtime services minio stop --head
    - cloudtik runtime services minio start --head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik runtime services minio stop
    - cloudtik runtime services minio start

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik runtime services minio stop --head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik runtime services minio stop
